version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elastic
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  dash_app:
    build:
      context: ./dash
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
    depends_on:
      - elasticsearch
    volumes:
      - .:/app
    environment:
      - FAST_API_URL=http://fast_api
      - FAST_API_PORT=8000

  fast_api:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
    volumes:
      - .:/app
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elastic

volumes:
  elasticsearch-data:


networks:
  default:
    name: my_project_network
